# fly.toml app configuration file generated for liga-lessons-monorepo on 2023-08-20T08:42:55Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "liga-lessons-monorepo"
primary_region = "ams"

[build]
  image = "ghcr.io/petr-nazarov/liga-lessons-monorepo:0.0.1"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
