# fly.toml app configuration file generated for liga-lessons-monorepo-server on 2023-08-27T12:12:22Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "liga-lessons-monorepo-server"
primary_region = "ams"

[build]
  image = "ghcr.io/petr-nazarov/liga-lessons-monorepo/server:latest"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
