name: Before closing pull request
on:
  pull_request:
  push:
      branches:
        - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install global deps
        run: npm i -g yarn

      - name: cache
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key:  node_modules-${{ github.ref_name }}-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            node_modules-${{ github.ref_name  }}-
            node_modules-master-
            node_modules-main
            node_modules-

      - name: Install dependencies
        if: ${{ steps.cache-dependencies.outputs.cache-hit != 'true'  }}
        run: yarn 
      
      - name: Lint
        run: yarn lint
  test:
    runs-on: ubuntu-latest
    needs: lint
    env:
      DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      
      - name: Install global deps
        run: npm i -g yarn  typescript@4.9.5 @nestjs/cli@9.4.0
      
      - name: cache
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key:  node_modules-${{ github.ref_name }}-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            node_modules-${{ github.ref_name  }}-
            node_modules-master-
            node_modules-main
            node_modules-

      - name: Install dependencies
        if: ${{ steps.cache-dependencies.outputs.cache-hit != 'true'  }}
        run: yarn 
      
      - name: Install Doppler
        run: (curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh || wget -t 3 -qO- https://cli.doppler.com/install.sh) | sudo sh
      
      - name: Build
        run: yarn build
      
      - name: Set up test env
        run: yarn env:test:up
      
      - name: Run test
        run: yarn test
      
      - name: Tear down tes env
        run: yarn env:test:down
