name: Release
on:
  push:
    tags:
      - '**'
jobs:
  publish-server-artifacts:
    name: Publish server docker image to container registry
    runs-on: ubuntu-latest
    permissions:
      contents: read 
      packages: write 
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Get current version of the package
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: ./apps/server

      # - name: Log in to registry
      #   run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u petr-nazarov --password-stdin
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: petr-nazarov
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/petr-nazarov/liga-lessons-monorepo/server
          tags: |
            type=ref,event=branch
            type=raw,value=github-{{sha}}
            type=raw,value=v${{ steps.package-version.outputs.current-version }}
          flavor: |
            latest=true
            prefix=
            suffix=

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/server/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          provenance: false
          build-args: |
            APP=server
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
